[server]
port = 5555
 
[node]
detect-drivers = false
 
[relay]
url = "http://localhost:4729"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:automationName\": \"UiAutomator2\"}"
]