[server]
port = 5565
 
[node]
detect-drivers = false
 
[relay]
url = "http://localhost:4733"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"iOS\", \"appium:automationName\": \"XCUITest\", \"appium:deviceName\": \"iPhone 15 Pro Max\"}"
]